### ISSUE TITLE
Importer from OpenStreetMap to database

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/road-graph-tool#4]
Importer from Open Street Map to a database.

Use [osm2pgsq ](https://osm2pgsql.org/) with [FleX output](https://osm2pgsql.org/doc/manual.html#the-flex-output).

- [x]  upload with all tags:
    - all nodes
    - all ways
    - all relations
- [x] Filtration by
    - geographic properties ([osmium](https://osmcode.org/libosmium/))
    - tags (osmium or flex output)
-  [x] Tests using pytest

osm map source:
- https://download.geofabrik.de/

**Comment by domupls** [comment]
- [ ] Add support for Linux and Windows
