### ISSUE TITLE
Update `config-EXAMPLE.ini` 

### ISSUE THREAD

**Issue by zlochina** [aicenter/road-graph-tool#53]
- Update `config-EXAMPLE.ini` with all potentially needed config key-value pairs
- Update class `CredentialsConfig` function `__init__` to set default values for any key, that hasn't already. E.g. for these config keys there is not default value:
```py
        self.username = config['database']['username']
        self.db_password = config['database']['db_password']
        self.db_host = config['database']['db_host']
        self.db_name = config['database']['db_name']
```

**Comment by zlochina** [comment]
@F-I-D-O, 
![image](https://github.com/user-attachments/assets/fd287329-aed5-4ba5-9610-3707f2cb1103)
I've thought about adding default values for those key-value pairs, which on the screenshot do not have `.get()` method, but it seems a little illogical to me. What do you think about raising an exception if any of the values of `username`, `db_host` or `db_name` are not specified? Like to inform the user to specify these highly **important** values.

**Comment by zlochina** [comment]
Something like this:
```py
        database = config["database"]

        if (
            "username" not in database
            or "db_host" not in database
            or "db_name" not in database
        ):
            raise Exception(
                'Either "username", "db_host" or "db_name" is missing from config.ini!'
            )

        self.db_server_port = int(database.get("db_server_port", "5432"))
        self.username = database["username"]
        self.db_password = database.get("db_password", "")
        self.db_host = database["db_host"]
        self.db_name = database["db_name"]

```

**Comment by F-I-D-O** [comment]
I think we can raise exception in case some parameter needed in all workflows is missing

**Comment by zlochina** [comment]
So all workflows, both existing and non-implemnted ones, dependent on database connection will need at least these 5 attributes: `db_server_port`, `username`, `db_password`, `db_host`, `db_name`.
Logically we would need to raise exception in `db.py` module. So I guess it leads to this system suggestion:
- `credentials_config.py` module will not raise an exception even if some of the needed args are missing.
- Instead of that, we would handle missing config values in critical methods of the modules, which are dependent on `credentials_config.py`. E.g.: in `db.py` module `get_new_psycopg2_connection` method would need to check if some of the 5 attributes mentioned on the beginning of this comment are missing, if yes an exception is raised and variable `config` is printed.
