### ISSUE TITLE
Update `importer/process.sh` to process long flag

### ISSUE THREAD

**Issue by zlochina** [aicenter/road-graph-tool#56]
![image](https://github.com/user-attachments/assets/c8ee410f-56b1-4c8c-a4bd-87afb9aea75e)
It is said in `README.md` to run `./process.sh -help`, which is processed as invalid argument:
 
<img width="605" alt="image" src="https://github.com/user-attachments/assets/0d108eb5-0a30-4c23-b754-37373473c53b">

- By convention long flags are prefixed with double `-`, so it should be as `--help`.
- Either mention using `./process.sh -h` in `README.md` or update `process.sh` to process `--help`

**Comment by domupls** [comment]
Thanks, this will be fixed with the linked pull request
