### ISSUE TITLE
`osm2pgsql` of version 2 has different behaviour with importing

### ISSUE THREAD

**Issue by zlochina** [aicenter/road-graph-tool#89]
Updated `osm2pgsql` to second version and there is difference in import. 
We can either stick to new documentation and rewrite our importing part according to new version, or specify in our project that the old version is preferred

**Comment by domupls** [comment]
I've updated the `*.lua` files in project to be compatible with the `2.0.0` version, but will mention that it can be compatible with `1.11.0` if `untagged_*()` functions are commented out. So far, the changes can be seen on `importer` branch but I'm gonna create pull request soon.

**Comment by zlochina** [comment]
We can update our `*.lua` files in such state, that depending on the variable of osm2pgsql we can decide to use specific functions for `2.0.0` version. Screenshot from the [osm2pgsql manual](https://osm2pgsql.org/doc/manual.html) of the version variable:
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/4f332214-7644-43ad-a4e9-771e92b63b56">

**Comment by domupls** [comment]
good idea, I'll implement that

**Comment by domupls** [comment]
good idea, I'll implement that
